lang: de
title: Con Espressione
logo:
  lg: assets/img/lg_imaginary_white.png
apps:
  - ../mozart_k331_3_batik
  - ../beethoven_fuer_elise
  - ../beethoven_op027_no2_mv1_bm_z
  - ../chopin_op10_no3_bm_magaloff
langMenuShow: true
langMenuItems:
  - en
  - de
